parameters:
  - name: host
    displayName: Linux Hostname (example.com)
    type: string
    default: jamacer
    values:
      - jamacer.jamesjonesconsulting.com
      - jambrix.jamesjonesconsulting.com
      - beebox.jamesjonesconsulting.com
      - build01.jamesjonesconsulting.com
      - build02.jamesjonesconsulting.com
      - indpc.jamesjonesconsulting.com
      - jamdb.jamesjonesconsulting.com
      - music.jamesjonesconsulting.com
      - lat5591.jamesjonesconsulting.com
      - jamtv.jamesjonesconsulting.com
      - charlottetv.jamesjonesconsulting.com

trigger: none
extends:
  template: installer.yml
  parameters:
    host: ${{ parameters.host }}
